version: '3'


services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.openshift
      # args:
      #  URL: http://192.168.99.100:8080/
    image: jenkins-ocp2
    container_name: jenkins
    hostname: jenkins
    volumes:
      - ./data/jenkins_openshift_home:/var/lib/jenkins:rw    
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
        - JAVA_MAX_HEAP_PARAM=-Xmx1024m
        - OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS=true
        - OPENSHIFT_ENABLE_OAUTH=true
#        - INSTALL_PLUGINS
 
