COMPOSE_FILE := dc-was9-standalone.yml
CONTAINER := was9base

default: all-ldap

base start :
	docker-compose  -f $(COMPOSE_FILE) up -d $(CONTAINER)
all-ldap:
	docker-compose  -f $(COMPOSE_FILE) up -d
stop:
	docker-compose  -f $(COMPOSE_FILE) down
restart:
	docker-compose  -f $(COMPOSE_FILE) stop $(CONTAINER); docker-compose  -f $(COMPOSE_FILE) start $(CONTAINER)

