version: "2"

networks:
  was9:
    driver: bridge

services:
  ldap:
    # docker run --env LDAP_ORGANISATION="2i" --env LDAP_DOMAIN="2i.at" --env LDAP_ADMIN_PASSWORD="admin" --detach --name ldap  -v ${PWD}/bootstrap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom  osixia/openldap:1.2.1 --copy-service --loglevel=info

    # docker exec ldap bash -c "ldapadd -x  -D cn=admin,dc=2i,dc=at  -w admin -H ldap:// -f  /import/ldap-content.ldif -c"
    # ldapsearch -x  -b dc=2i,dc=at -D cn=admin,dc=2i,dc=at -w admin

    # image: thikade/openldap:1.1.7-imported
    image: osixia/openldap:1.2.1
    container_name: ldap1
    hostname: ldap1
    environment:
      LDAP_ORGANISATION: 2i
      LDAP_DOMAIN: 2i.at
      LDAP_ADMIN_PASSWORD: admin
    expose:
      - "389"
      - "636"
    ports:
      - "10389:389"
      - "10636:636"
    volumes:
      - ${PWD}/bootstrap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    # entrypoint: "sh -c 'while true; do sleep 60; echo hello; done'"
    command: --copy-service --loglevel=debug
    networks:
      - was9

  ldap2:
    # docker run --env LDAP_ORGANISATION="2i" --env LDAP_DOMAIN="2i.at" --env LDAP_ADMIN_PASSWORD="admin" --detach --name ldap  -v ${PWD}/bootstrap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom  osixia/openldap:1.2.1 --copy-service --loglevel=info

    # docker exec ldap bash -c "ldapadd -x  -D cn=admin,dc=2i,dc=at  -w admin -H ldap:// -f  /import/ldap-content.ldif -c"
    # ldapsearch -x  -b dc=2i,dc=at -D cn=admin,dc=2i,dc=at -w admin

    # image: thikade/openldap:1.1.7-imported
    image: osixia/openldap:1.2.1
    container_name: ldap2
    hostname: ldap2
    environment:
      LDAP_ORGANISATION: 2i
      LDAP_DOMAIN: 2i.at
      LDAP_ADMIN_PASSWORD: admin
    expose:
      - "389"
      - "636"
    ports:
      - "20389:389"
      - "20636:636"
    volumes:
      - ${PWD}/bootstrap-ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    # entrypoint: "sh -c 'while true; do sleep 60; echo hello; done'"
    command: --copy-service --loglevel=info
    networks:
      - was9

  dmgr:
    image: wasnd9-cell-dmgr:9050
    container_name: dmgr
    hostname: dmgr
    environment:
      WASCONFIG_RUNAS_USER: wasadmin
      WASCONFIG_WAS_ROOT: /opt/IBM/WebSphere/AppServer
      WASCONFIG_PROFILE_PATH: /opt/IBM/WebSphere/AppServer/profiles/Dmgr01
      WASCONFIG_PROFILE_NAME: Dmgr01
      WASCONFIG_ADMIN_HOST: dmgr
      WASCONFIG_ADMIN_PORT: 8879
      WASCONFIG_ADMIN_USER: wasadmin
      WASCONFIG_ADMIN_PASS: wasadmin
      # JVM_EXTRA_CMD_ARGS: "-javaagent:/work/jmx_prometheus_javaagent-0.12.0.jar=2345:/work/jmx-config.yml"
      JVM_EXTRA_CMD_ARGS: "-javaagent:/work/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=2345:/work/jmx-config.yml"
    expose:
      - "9060"
      - "9043"
      - "9809"
      - "8879"
      - "9632"
      - "9401"
      - "9403"
      - "9402"
      - "9100"
      - "7277"
      - "9352"
      - "5555"
      - "7060"
      - "11005"
      - "11006"
      - "9420"
    ports:
      - "9060:9060"
      - "9043:9043"
    volumes:
      - $PRJ_ROOT/wasconfig:/wasconfig:rw
      - $PRJ_ROOT/was_configs:/config:rw
      - $PRJ_ROOT/dockerfiles/wasnd/nd/dmgr/jmx-config.yml:/work/jmx-config.yml:rw
      - $PRJ_ROOT/dockerfiles/wasnd/nd/dmgr/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar:/work/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar:ro
    networks:
      - was9

  node01:
    image: wasnd9-cell-node01
    container_name: node01
    depends_on:
      - dmgr
    environment:
      NODE_NAME: CustomNode01
      DMGR_HOST: dmgr
      DMGR_PORT: "8879"
    hostname: node01
    expose:
      - 2809
      - 9402
      - 9403
      - 9353
      - 9633
      - 9100
      - 11004
      - 11003
      - 9401
      - 7276
      - 7286
      - 5558
      - 5578
      - 5060
      - 5061
      - 8880
      - 9060
      - 9043
      - 9080
      - 9443
    ports:
      - "9080:9080"
      - "9443:9443"
    networks:
      - was9

  node02:
    image: wasnd9-cell-node02
    container_name: node02
    hostname: node02
    depends_on:
      - dmgr
    environment:
      NODE_NAME: CustomNode02
      DMGR_HOST: dmgr
      DMGR_PORT: "8879"
    expose:
      - 2809
      - 9402
      - 9403
      - 9353
      - 9633
      - 9100
      - 11004
      - 11003
      - 9401
      - 7276
      - 7286
      - 5558
      - 5578
      - 5060
      - 5061
      - 8880
      - 9060
      - 9043
      - 9080
      - 9443
    networks:
      - was9
