PHONY: build build-ssh

# docker build -t wasnd-cell-ssh-dmgr -f Dockerfile-ssh-dmgr .
build-ssh:
	docker build -t wasnd-cell-ssh-node01 -f Dockerfile-ssh-node01 .
	docker build -t wasnd-cell-ssh-node02 -f Dockerfile-ssh-node02 .
