version: '2'

networks:
  ansible-demo-network:
    driver: bridge

services:
  ansible-master:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #  URL: http://192.168.99.100:8080/
    image: thikade/ansible:2.7-ubuntu
    container_name: ansible-master
    hostname: ansible-master
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    volumes:
      - ./volumes/default:/shared:rw
      - ../../ansible/src/ansible:/shared:rw
#      - /c/Users/ThomasHikade/Documents/GitHub/ansible/src/ansible:/ansible-shared:rw
    networks:
      - ansible-demo-network

  ansible-node01:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #  URL: http://192.168.99.100:8080/
    image: thikade/ansible:2.7-ubuntu
    container_name: ansible-node01
    hostname: ansible-node01
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    expose:
      - "22"
      - "80"
      - "443"
      - "8080"
      - "9080"
    ports:
      - "10080:80"
      - "10443:443"
      - "18080:8080"
      - "19080:9080"
    volumes:
      - ./volumes/default:/shared:rw
    networks:
      - ansible-demo-network
